version: '3.9'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
          - '5432:5432'
        volumes:
          - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
          - keploy-network
    
    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: bunSqlApp
      ports:
        - "4040:4040"
      depends_on:
        - postgres
      networks:
        - keploy-network

networks:
  keploy-network:
    external: true